// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: glutton.proto

package glutton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteMode int32

const (
	// Overwrite the destination entirely
	WriteMode_WRITE_MODE_TRUNCATE WriteMode = 0
	// Write on top of the existing data
	WriteMode_WRITE_MODE_OVERWRITE WriteMode = 1
	// Write on top of the existing data at a per-key cursor that advances
	// past each write and wraps at the end, so repeated writes walk the
	// whole array instead of re-dirtying the same prefix. RAM only.
	WriteMode_WRITE_MODE_OVERWRITE_ROTATE WriteMode = 2
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_TRUNCATE",
		1: "WRITE_MODE_OVERWRITE",
		2: "WRITE_MODE_OVERWRITE_ROTATE",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_TRUNCATE":         0,
		"WRITE_MODE_OVERWRITE":        1,
		"WRITE_MODE_OVERWRITE_ROTATE": 2,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_glutton_proto_enumTypes[0].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_glutton_proto_enumTypes[0]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{0}
}

// ReadMode selects how much of the file ReadDisk sends back.
type ReadMode int32

const (
	// Return the file's bytes in ReadDiskResponse.data alongside its digest.
	ReadMode_READ_MODE_DATA ReadMode = 0
	// Return only size and sha256; ReadDiskResponse.data is empty. The digest
	// is the same one READ_MODE_DATA returns, so either mode can verify.
	ReadMode_READ_MODE_DIGEST_ONLY ReadMode = 1
)

// Enum value maps for ReadMode.
var (
	ReadMode_name = map[int32]string{
		0: "READ_MODE_DATA",
		1: "READ_MODE_DIGEST_ONLY",
	}
	ReadMode_value = map[string]int32{
		"READ_MODE_DATA":        0,
		"READ_MODE_DIGEST_ONLY": 1,
	}
)

func (x ReadMode) Enum() *ReadMode {
	p := new(ReadMode)
	*p = x
	return p
}

func (x ReadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_glutton_proto_enumTypes[1].Descriptor()
}

func (ReadMode) Type() protoreflect.EnumType {
	return &file_glutton_proto_enumTypes[1]
}

func (x ReadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadMode.Descriptor instead.
func (ReadMode) EnumDescriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{1}
}

type WriteRAMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the array to be written to
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// size of bytes to be written, with an optional unit suffix (e.g. "2Gi")
	Size          string    `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	WriteMode     WriteMode `protobuf:"varint,3,opt,name=write_mode,json=writeMode,proto3,enum=glutton.WriteMode" json:"write_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRAMRequest) Reset() {
	*x = WriteRAMRequest{}
	mi := &file_glutton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRAMRequest) ProtoMessage() {}

func (x *WriteRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRAMRequest.ProtoReflect.Descriptor instead.
func (*WriteRAMRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRAMRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRAMRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *WriteRAMRequest) GetWriteMode() WriteMode {
	if x != nil {
		return x.WriteMode
	}
	return WriteMode_WRITE_MODE_TRUNCATE
}

type WriteRAMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRAMResponse) Reset() {
	*x = WriteRAMResponse{}
	mi := &file_glutton_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRAMResponse) ProtoMessage() {}

func (x *WriteRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRAMResponse.ProtoReflect.Descriptor instead.
func (*WriteRAMResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{1}
}

type ReadRAMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the array to be read
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// size of bytes to walk, with an optional unit suffix (e.g. "2Gi");
	// empty walks the whole array
	Size          string `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRAMRequest) Reset() {
	*x = ReadRAMRequest{}
	mi := &file_glutton_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRAMRequest) ProtoMessage() {}

func (x *ReadRAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRAMRequest.ProtoReflect.Descriptor instead.
func (*ReadRAMRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRAMRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRAMRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type ReadRAMResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total size of bytes walked
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// XOR of the sampled bytes, so the reads are observable
	Checksum      uint32 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRAMResponse) Reset() {
	*x = ReadRAMResponse{}
	mi := &file_glutton_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRAMResponse) ProtoMessage() {}

func (x *ReadRAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRAMResponse.ProtoReflect.Descriptor instead.
func (*ReadRAMResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRAMResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadRAMResponse) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type WriteDiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the file to be written to
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// size of bytes to be written
	Size          int32     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	WriteMode     WriteMode `protobuf:"varint,3,opt,name=write_mode,json=writeMode,proto3,enum=glutton.WriteMode" json:"write_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDiskRequest) Reset() {
	*x = WriteDiskRequest{}
	mi := &file_glutton_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDiskRequest) ProtoMessage() {}

func (x *WriteDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDiskRequest.ProtoReflect.Descriptor instead.
func (*WriteDiskRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{4}
}

func (x *WriteDiskRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteDiskRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteDiskRequest) GetWriteMode() WriteMode {
	if x != nil {
		return x.WriteMode
	}
	return WriteMode_WRITE_MODE_TRUNCATE
}

type WriteDiskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// size of the file after the write
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// sha256 of the whole file after the write
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDiskResponse) Reset() {
	*x = WriteDiskResponse{}
	mi := &file_glutton_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDiskResponse) ProtoMessage() {}

func (x *WriteDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDiskResponse.ProtoReflect.Descriptor instead.
func (*WriteDiskResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{5}
}

func (x *WriteDiskResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteDiskResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type ReadDiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the file to be read from
	Key           string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ReadMode      ReadMode `protobuf:"varint,2,opt,name=read_mode,json=readMode,proto3,enum=glutton.ReadMode" json:"read_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDiskRequest) Reset() {
	*x = ReadDiskRequest{}
	mi := &file_glutton_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDiskRequest) ProtoMessage() {}

func (x *ReadDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDiskRequest.ProtoReflect.Descriptor instead.
func (*ReadDiskRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{6}
}

func (x *ReadDiskRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadDiskRequest) GetReadMode() ReadMode {
	if x != nil {
		return x.ReadMode
	}
	return ReadMode_READ_MODE_DATA
}

type ReadDiskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total size of bytes read
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// sha256 of bytes read
	Sha256 []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// data read from the file. Empty under READ_MODE_DIGEST_ONLY.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDiskResponse) Reset() {
	*x = ReadDiskResponse{}
	mi := &file_glutton_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDiskResponse) ProtoMessage() {}

func (x *ReadDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDiskResponse.ProtoReflect.Descriptor instead.
func (*ReadDiskResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{7}
}

func (x *ReadDiskResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadDiskResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ReadDiskResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OpenFDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total number of FDs for the glutton to open
	Count         int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFDRequest) Reset() {
	*x = OpenFDRequest{}
	mi := &file_glutton_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFDRequest) ProtoMessage() {}

func (x *OpenFDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFDRequest.ProtoReflect.Descriptor instead.
func (*OpenFDRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{8}
}

func (x *OpenFDRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OpenFDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFDResponse) Reset() {
	*x = OpenFDResponse{}
	mi := &file_glutton_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFDResponse) ProtoMessage() {}

func (x *OpenFDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFDResponse.ProtoReflect.Descriptor instead.
func (*OpenFDResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{9}
}

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message to be echoed back from the ping
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_glutton_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{10}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message echoed back
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_glutton_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_glutton_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{12}
}

func (x *GossipRequest) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_glutton_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{13}
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_glutton_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{14}
}

func (x *Peer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Peer) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type BurnCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall-clock time to keep burning, in milliseconds.
	DurationMs int64 `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Number of goroutines burning concurrently; values < 1 read as 1.
	Parallelism   int32 `protobuf:"varint,2,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnCPURequest) Reset() {
	*x = BurnCPURequest{}
	mi := &file_glutton_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnCPURequest) ProtoMessage() {}

func (x *BurnCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnCPURequest.ProtoReflect.Descriptor instead.
func (*BurnCPURequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{15}
}

func (x *BurnCPURequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BurnCPURequest) GetParallelism() int32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

type BurnCPUResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total hash iterations completed across all goroutines, so the burn
	// is observable and cannot be optimized away.
	Iterations    int64 `protobuf:"varint,1,opt,name=iterations,proto3" json:"iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnCPUResponse) Reset() {
	*x = BurnCPUResponse{}
	mi := &file_glutton_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnCPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnCPUResponse) ProtoMessage() {}

func (x *BurnCPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnCPUResponse.ProtoReflect.Descriptor instead.
func (*BurnCPUResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{16}
}

func (x *BurnCPUResponse) GetIterations() int64 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the file the payload is written to
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// the bytes to write, carried in the request body over the network
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// append to the file instead of truncating it
	Append        bool `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_glutton_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{17}
}

func (x *IngestRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IngestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestRequest) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// size of the file after the write
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// sha256 of the payload as received, so the caller can verify transport
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_glutton_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{18}
}

func (x *IngestResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IngestResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type UseCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of parallel goroutines to spin, each targeting duty_cycle
	// fraction of one CPU core. Set to 0 to stop all CPU load.
	NumCores int32 `protobuf:"varint,1,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	// Fraction of CPU time each goroutine should consume, in [0.0, 1.0].
	DutyCycle float64 `protobuf:"fixed64,2,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	// Per-goroutine work/sleep cycle length in milliseconds. Defaults to
	// 100 when 0 or unset. Smaller values give smoother load at the cost
	// of scheduler and timer-wheel overhead.
	CycleLengthMs int32 `protobuf:"varint,3,opt,name=cycle_length_ms,json=cycleLengthMs,proto3" json:"cycle_length_ms,omitempty"`
	// Whether num_cores should be capped at GOMAXPROCS. Defaults to true
	// when unset. Uncapped (false) lets the caller force oversubscription
	// to test scheduler pressure, at the cost of goroutines running below
	// their target duty cycle.
	CapAtGomaxprocs *bool `protobuf:"varint,4,opt,name=cap_at_gomaxprocs,json=capAtGomaxprocs,proto3,oneof" json:"cap_at_gomaxprocs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UseCPURequest) Reset() {
	*x = UseCPURequest{}
	mi := &file_glutton_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCPURequest) ProtoMessage() {}

func (x *UseCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCPURequest.ProtoReflect.Descriptor instead.
func (*UseCPURequest) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{19}
}

func (x *UseCPURequest) GetNumCores() int32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *UseCPURequest) GetDutyCycle() float64 {
	if x != nil {
		return x.DutyCycle
	}
	return 0
}

func (x *UseCPURequest) GetCycleLengthMs() int32 {
	if x != nil {
		return x.CycleLengthMs
	}
	return 0
}

func (x *UseCPURequest) GetCapAtGomaxprocs() bool {
	if x != nil && x.CapAtGomaxprocs != nil {
		return *x.CapAtGomaxprocs
	}
	return false
}

type UseCPUResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of goroutines actually spun. Equals the request's
	// num_cores unless it was capped at GOMAXPROCS.
	NumCores      int32 `protobuf:"varint,1,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCPUResponse) Reset() {
	*x = UseCPUResponse{}
	mi := &file_glutton_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCPUResponse) ProtoMessage() {}

func (x *UseCPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glutton_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCPUResponse.ProtoReflect.Descriptor instead.
func (*UseCPUResponse) Descriptor() ([]byte, []int) {
	return file_glutton_proto_rawDescGZIP(), []int{20}
}

func (x *UseCPUResponse) GetNumCores() int32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

var File_glutton_proto protoreflect.FileDescriptor

const file_glutton_proto_rawDesc = "" +
	"\n" +
	"\rglutton.proto\x12\aglutton\"j\n" +
	"\x0fWriteRAMRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x121\n" +
	"\n" +
	"write_mode\x18\x03 \x01(\x0e2\x12.glutton.WriteModeR\twriteMode\"\x12\n" +
	"\x10WriteRAMResponse\"6\n" +
	"\x0eReadRAMRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"A\n" +
	"\x0fReadRAMResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\"k\n" +
	"\x10WriteDiskRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x121\n" +
	"\n" +
	"write_mode\x18\x03 \x01(\x0e2\x12.glutton.WriteModeR\twriteMode\"?\n" +
	"\x11WriteDiskResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"S\n" +
	"\x0fReadDiskRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\tread_mode\x18\x02 \x01(\x0e2\x11.glutton.ReadModeR\breadMode\"R\n" +
	"\x10ReadDiskResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"%\n" +
	"\rOpenFDRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x10\n" +
	"\x0eOpenFDResponse\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\rGossipRequest\x12#\n" +
	"\x05peers\x18\x01 \x03(\v2\r.glutton.PeerR\x05peers\"\x10\n" +
	"\x0eGossipResponse\"5\n" +
	"\x04Peer\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"S\n" +
	"\x0eBurnCPURequest\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12 \n" +
	"\vparallelism\x18\x02 \x01(\x05R\vparallelism\"1\n" +
	"\x0fBurnCPUResponse\x12\x1e\n" +
	"\n" +
	"iterations\x18\x01 \x01(\x03R\n" +
	"iterations\"S\n" +
	"\rIngestRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06append\x18\x03 \x01(\bR\x06append\"<\n" +
	"\x0eIngestResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"\xba\x01\n" +
	"\rUseCPURequest\x12\x1b\n" +
	"\tnum_cores\x18\x01 \x01(\x05R\bnumCores\x12\x1d\n" +
	"\n" +
	"duty_cycle\x18\x02 \x01(\x01R\tdutyCycle\x12&\n" +
	"\x0fcycle_length_ms\x18\x03 \x01(\x05R\rcycleLengthMs\x12/\n" +
	"\x11cap_at_gomaxprocs\x18\x04 \x01(\bH\x00R\x0fcapAtGomaxprocs\x88\x01\x01B\x14\n" +
	"\x12_cap_at_gomaxprocs\"-\n" +
	"\x0eUseCPUResponse\x12\x1b\n" +
	"\tnum_cores\x18\x01 \x01(\x05R\bnumCores*_\n" +
	"\tWriteMode\x12\x17\n" +
	"\x13WRITE_MODE_TRUNCATE\x10\x00\x12\x18\n" +
	"\x14WRITE_MODE_OVERWRITE\x10\x01\x12\x1f\n" +
	"\x1bWRITE_MODE_OVERWRITE_ROTATE\x10\x02*9\n" +
	"\bReadMode\x12\x12\n" +
	"\x0eREAD_MODE_DATA\x10\x00\x12\x19\n" +
	"\x15READ_MODE_DIGEST_ONLY\x10\x012\x80\x05\n" +
	"\aGlutton\x12A\n" +
	"\bWriteRAM\x12\x18.glutton.WriteRAMRequest\x1a\x19.glutton.WriteRAMResponse\"\x00\x12>\n" +
	"\aReadRAM\x12\x17.glutton.ReadRAMRequest\x1a\x18.glutton.ReadRAMResponse\"\x00\x12D\n" +
	"\tWriteDisk\x12\x19.glutton.WriteDiskRequest\x1a\x1a.glutton.WriteDiskResponse\"\x00\x12A\n" +
	"\bReadDisk\x12\x18.glutton.ReadDiskRequest\x1a\x19.glutton.ReadDiskResponse\"\x00\x12;\n" +
	"\x06OpenFD\x12\x16.glutton.OpenFDRequest\x1a\x17.glutton.OpenFDResponse\"\x00\x125\n" +
	"\x04Ping\x12\x14.glutton.PingRequest\x1a\x15.glutton.PingResponse\"\x00\x12;\n" +
	"\x06Gossip\x12\x16.glutton.GossipRequest\x1a\x17.glutton.GossipResponse\"\x00\x12>\n" +
	"\aBurnCPU\x12\x17.glutton.BurnCPURequest\x1a\x18.glutton.BurnCPUResponse\"\x00\x12;\n" +
	"\x06Ingest\x12\x16.glutton.IngestRequest\x1a\x17.glutton.IngestResponse\"\x00\x12;\n" +
	"\x06UseCPU\x12\x16.glutton.UseCPURequest\x1a\x17.glutton.UseCPUResponse\"\x00B=Z;github.com/agent-substrate/substrate/internal/proto/gluttonb\x06proto3"

var (
	file_glutton_proto_rawDescOnce sync.Once
	file_glutton_proto_rawDescData []byte
)

func file_glutton_proto_rawDescGZIP() []byte {
	file_glutton_proto_rawDescOnce.Do(func() {
		file_glutton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_glutton_proto_rawDesc), len(file_glutton_proto_rawDesc)))
	})
	return file_glutton_proto_rawDescData
}

var file_glutton_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_glutton_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_glutton_proto_goTypes = []any{
	(WriteMode)(0),            // 0: glutton.WriteMode
	(ReadMode)(0),             // 1: glutton.ReadMode
	(*WriteRAMRequest)(nil),   // 2: glutton.WriteRAMRequest
	(*WriteRAMResponse)(nil),  // 3: glutton.WriteRAMResponse
	(*ReadRAMRequest)(nil),    // 4: glutton.ReadRAMRequest
	(*ReadRAMResponse)(nil),   // 5: glutton.ReadRAMResponse
	(*WriteDiskRequest)(nil),  // 6: glutton.WriteDiskRequest
	(*WriteDiskResponse)(nil), // 7: glutton.WriteDiskResponse
	(*ReadDiskRequest)(nil),   // 8: glutton.ReadDiskRequest
	(*ReadDiskResponse)(nil),  // 9: glutton.ReadDiskResponse
	(*OpenFDRequest)(nil),     // 10: glutton.OpenFDRequest
	(*OpenFDResponse)(nil),    // 11: glutton.OpenFDResponse
	(*PingRequest)(nil),       // 12: glutton.PingRequest
	(*PingResponse)(nil),      // 13: glutton.PingResponse
	(*GossipRequest)(nil),     // 14: glutton.GossipRequest
	(*GossipResponse)(nil),    // 15: glutton.GossipResponse
	(*Peer)(nil),              // 16: glutton.Peer
	(*BurnCPURequest)(nil),    // 17: glutton.BurnCPURequest
	(*BurnCPUResponse)(nil),   // 18: glutton.BurnCPUResponse
	(*IngestRequest)(nil),     // 19: glutton.IngestRequest
	(*IngestResponse)(nil),    // 20: glutton.IngestResponse
	(*UseCPURequest)(nil),     // 21: glutton.UseCPURequest
	(*UseCPUResponse)(nil),    // 22: glutton.UseCPUResponse
}
var file_glutton_proto_depIdxs = []int32{
	0,  // 0: glutton.WriteRAMRequest.write_mode:type_name -> glutton.WriteMode
	0,  // 1: glutton.WriteDiskRequest.write_mode:type_name -> glutton.WriteMode
	1,  // 2: glutton.ReadDiskRequest.read_mode:type_name -> glutton.ReadMode
	16, // 3: glutton.GossipRequest.peers:type_name -> glutton.Peer
	2,  // 4: glutton.Glutton.WriteRAM:input_type -> glutton.WriteRAMRequest
	4,  // 5: glutton.Glutton.ReadRAM:input_type -> glutton.ReadRAMRequest
	6,  // 6: glutton.Glutton.WriteDisk:input_type -> glutton.WriteDiskRequest
	8,  // 7: glutton.Glutton.ReadDisk:input_type -> glutton.ReadDiskRequest
	10, // 8: glutton.Glutton.OpenFD:input_type -> glutton.OpenFDRequest
	12, // 9: glutton.Glutton.Ping:input_type -> glutton.PingRequest
	14, // 10: glutton.Glutton.Gossip:input_type -> glutton.GossipRequest
	17, // 11: glutton.Glutton.BurnCPU:input_type -> glutton.BurnCPURequest
	19, // 12: glutton.Glutton.Ingest:input_type -> glutton.IngestRequest
	21, // 13: glutton.Glutton.UseCPU:input_type -> glutton.UseCPURequest
	3,  // 14: glutton.Glutton.WriteRAM:output_type -> glutton.WriteRAMResponse
	5,  // 15: glutton.Glutton.ReadRAM:output_type -> glutton.ReadRAMResponse
	7,  // 16: glutton.Glutton.WriteDisk:output_type -> glutton.WriteDiskResponse
	9,  // 17: glutton.Glutton.ReadDisk:output_type -> glutton.ReadDiskResponse
	11, // 18: glutton.Glutton.OpenFD:output_type -> glutton.OpenFDResponse
	13, // 19: glutton.Glutton.Ping:output_type -> glutton.PingResponse
	15, // 20: glutton.Glutton.Gossip:output_type -> glutton.GossipResponse
	18, // 21: glutton.Glutton.BurnCPU:output_type -> glutton.BurnCPUResponse
	20, // 22: glutton.Glutton.Ingest:output_type -> glutton.IngestResponse
	22, // 23: glutton.Glutton.UseCPU:output_type -> glutton.UseCPUResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_glutton_proto_init() }
func file_glutton_proto_init() {
	if File_glutton_proto != nil {
		return
	}
	file_glutton_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_glutton_proto_rawDesc), len(file_glutton_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_glutton_proto_goTypes,
		DependencyIndexes: file_glutton_proto_depIdxs,
		EnumInfos:         file_glutton_proto_enumTypes,
		MessageInfos:      file_glutton_proto_msgTypes,
	}.Build()
	File_glutton_proto = out.File
	file_glutton_proto_goTypes = nil
	file_glutton_proto_depIdxs = nil
}
